version: '3.8'
services:
  app:
    build: .
    container_name: nestjs-app
    restart: always
    ports:
      - "3000:3000"
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      - redis

  redis:
    image: redis
    container_name: my-redis
    restart: always
    ports:
      - "6379:6379"
