version: '3.8'

services:
  redis:
    image: "redis:alpine"
    container_name: redis_service
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  redis_data:
